#!/bin/bash
#
# This file performs a test of the autojudge system. It can run whatever you feel important to test the autojudge
# and the script files that are included in the problem package

mkdir -p testdir
cd testdir

cat > test.pas <<EOF
program teste(input,output);

var lido:string;
begin
  read(lido);
  writeln(lido);
end.
EOF
cat > test.in <<EOF
inputdata
EOF

TL=2
REP=10
chmod 755 ../../compile/pas
../../compile/pas test.pas test.exe $TL
chmod 755 ../../run/pas
../../run/pas test.exe test.in $TL $REP
if [ -r stdout0 ]; then
  output=`cat stdout0`
  if [ "$output" != "inputdata" ]; then
    echo "ERROR"
    exit 1
  fi
else
  echo "ERROR"
  exit 1
fi
echo "TEST PASSED"
cd ..
exit 0
